// renderers/react/src/v0_9/catalog/basic/components/Divider.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createComponentImplementation} from '../../../adapter';
import {DividerApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {LEAF_MARGIN} from '../utils';

export const Divider = createComponentImplementation(DividerApi, ({props}) => {
  const isVertical = props.axis === 'vertical';
  const style: React.CSSProperties = {
    margin: LEAF_MARGIN,
    border: 'none',
    backgroundColor: '#ccc',
  };

  if (isVertical) {
    style.width = '1px';
    style.height = '100%';
  } else {
    style.width = '100%';
    style.height = '1px';
  }

  return <div style={style} />;
});

// renderers/lit/src/v0_9/catalogs/basic/components/Divider.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing } from "lit";
import { customElement } from "lit/decorators.js";
import { DividerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { A2uiLitElement, A2uiController } from "@a2ui/lit/v0_9";

@customElement("a2ui-divider")
export class A2uiDividerElement extends A2uiLitElement<typeof DividerApi> {
  protected createController() {
    return new A2uiController(this, DividerApi);
  }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    return props.axis === "vertical"
      ? html`<div
          class="a2ui-divider-vertical"
          style="width: 1px; background: #ccc; height: 100%;"
        ></div>`
      : html`<hr
          class="a2ui-divider"
          style="border: none; border-top: 1px solid #ccc; margin: 16px 0;"
        />`;
  }
}

export const A2uiDivider = {
  ...DividerApi,
  tagName: "a2ui-divider",
};
