// renderers/react/src/v0_9/catalog/basic/components/ChoicePicker.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, {useState} from 'react';
import {createComponentImplementation} from '../../../adapter';
import {ChoicePickerApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {LEAF_MARGIN, STANDARD_BORDER, STANDARD_RADIUS} from '../utils';

// The type of an option is deeply nested into the ChoicePickerApi schema, and
// it seems z.infer is not inferring it correctly (?). We use `any` for now.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type _Option = any;

export const ChoicePicker = createComponentImplementation(ChoicePickerApi, ({props, context}) => {
  const [filter, setFilter] = useState('');

  const values = Array.isArray(props.value) ? props.value : [];
  const isMutuallyExclusive = props.variant === 'mutuallyExclusive';

  const onToggle = (val: string) => {
    if (isMutuallyExclusive) {
      props.setValue([val]);
    } else {
      const newValues = values.includes(val)
        ? values.filter((v: string) => v !== val)
        : [...values, val];
      props.setValue(newValues);
    }
  };

  const options = (props.options || []).filter(
    (opt: _Option) =>
      !props.filterable ||
      filter === '' ||
      String(opt.label).toLowerCase().includes(filter.toLowerCase())
  );

  const containerStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    margin: LEAF_MARGIN,
    width: '100%',
  };

  const listStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: props.displayStyle === 'chips' ? 'row' : 'column',
    flexWrap: props.displayStyle === 'chips' ? 'wrap' : 'nowrap',
    gap: '8px',
  };

  return (
    <div style={containerStyle}>
      {props.label && <strong style={{fontSize: '14px'}}>{props.label}</strong>}
      {props.filterable && (
        <input
          type="text"
          placeholder="Filter options..."
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          style={{padding: '4px 8px', border: STANDARD_BORDER, borderRadius: STANDARD_RADIUS}}
        />
      )}
      <div style={listStyle}>
        {options.map((opt: _Option, i: number) => {
          const isSelected = values.includes(opt.value);
          if (props.displayStyle === 'chips') {
            return (
              <button
                key={i}
                onClick={() => onToggle(opt.value)}
                style={{
                  padding: '4px 12px',
                  borderRadius: '16px',
                  border: isSelected
                    ? '1px solid var(--a2ui-primary-color, #007bff)'
                    : STANDARD_BORDER,
                  backgroundColor: isSelected ? 'var(--a2ui-primary-color, #007bff)' : '#fff',
                  color: isSelected ? '#fff' : 'inherit',
                  cursor: 'pointer',
                  fontSize: '12px',
                }}
              >
                {opt.label}
              </button>
            );
          }
          return (
            <label
              key={i}
              style={{display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer'}}
            >
              <input
                type={isMutuallyExclusive ? 'radio' : 'checkbox'}
                checked={isSelected}
                onChange={() => onToggle(opt.value)}
                name={isMutuallyExclusive ? `choice-${context.componentModel.id}` : undefined}
              />
              <span style={{fontSize: '14px'}}>{opt.label}</span>
            </label>
          );
        })}
      </div>
    </div>
  );
});

// renderers/angular/src/v0_9/catalog/basic/choice-picker.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';
import { BoundProperty } from '../../core/types';

/**
 * Angular implementation of the A2UI ChoicePicker component (v0.9).
 *
 * Renders a set of options as either radio buttons/checkboxes or chips.
 * Supports both single and multiple selection.
 */
@Component({
  selector: 'a2ui-v09-choice-picker',
  standalone: true,
  imports: [],
  template: `
    <div class="a2ui-choice-picker">
      <!-- Chips Variant -->
      @if (displayStyle() === 'chips') {
        <div class="a2ui-chips-group">
          @for (choice of choices(); track choice.value) {
            <button
              class="a2ui-chip"
              [class.active]="isSelected(choice.value)"
              (click)="toggleActive(choice.value)"
            >
              {{ choice.label }}
            </button>
          }
        </div>
      } @else {
        <!-- Checkbox/Radio Variant -->
        <div class="a2ui-options-group">
          @for (choice of choices(); track choice.value) {
            <label class="a2ui-option-label">
              <input
                [type]="isMultiple() ? 'checkbox' : 'radio'"
                [name]="componentId()"
                [value]="choice.value"
                [checked]="isSelected(choice.value)"
                (change)="onCheckChange(choice.value, $event)"
                class="a2ui-option-input"
              />
              <span class="a2ui-option-text">{{ choice.label }}</span>
            </label>
          }
        </div>
      }
    </div>
  `,
  styles: [
    `
      .a2ui-choice-picker {
        width: 100%;
      }
      .a2ui-options-group {
        display: flex;
        flex-direction: column;
        gap: 8px;
      }
      .a2ui-option-label {
        display: flex;
        align-items: center;
        gap: 8px;
        cursor: pointer;
      }
      .a2ui-option-input {
        width: 18px;
        height: 18px;
      }
      .a2ui-chips-group {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
      }
      .a2ui-chip {
        padding: 4px 12px;
        border-radius: 16px;
        border: 1px solid #ccc;
        background: white;
        cursor: pointer;
        transition: all 0.2s;
      }
      .a2ui-chip.active {
        background-color: #007bff;
        color: white;
        border-color: #007bff;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChoicePickerComponent {
  /**
   * Reactive properties resolved from the A2UI {@link ComponentModel}.
   *
   * Expected properties:
   * - `value`: The currently selected value(s).
   * - `choices` or `options`: List of choice objects (label and value).
   * - `displayStyle`: How to render the choices ('default' or 'chips').
   * - `variant`: Selection mode ('singleSelection' or 'multipleSelection').
   */
  props = input<Record<string, BoundProperty>>({});
  surfaceId = input.required<string>();
  componentId = input<string>();
  dataContextPath = input<string>('/');

  displayStyle = computed(() => this.props()['displayStyle']?.value());
  choices = computed(
    () => this.props()['choices']?.value() || this.props()['options']?.value() || [],
  );
  variant = computed(() => this.props()['variant']?.value());
  selectedValue = computed(() => this.props()['value']?.value());

  isMultiple(): boolean {
    return this.variant() === 'multipleSelection';
  }

  isSelected(value: string): boolean {
    const selected = this.selectedValue();
    if (Array.isArray(selected)) {
      return selected.includes(value);
    }
    return selected === value;
  }

  onCheckChange(value: string, event: Event) {
    const checked = (event.target as HTMLInputElement).checked;
    this.updateValue(value, checked);
  }

  toggleActive(value: string) {
    const current = this.isSelected(value);
    this.updateValue(value, !current);
  }

  private updateValue(value: string, active: boolean) {
    const current = this.selectedValue();
    if (this.isMultiple()) {
      let next = Array.isArray(current) ? [...current] : [];
      if (active) {
        if (!next.includes(value)) next.push(value);
      } else {
        next = next.filter((v: any) => v !== value);
      }
      this.props()['value']?.onUpdate(next);
    } else {
      if (active) {
        this.props()['value']?.onUpdate(value);
      }
    }
  }
}
